//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventCalenderAng.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartAt { get; set; }
        public Nullable<System.DateTime> EndAt { get; set; }
        public bool IsFullDay { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> LocationID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Location Location { get; set; }
    }
}
